import 'package:doaya_ui/doaya_ui.dart';

import '../l10n/app_localizations.dart';

/// «المظهر» in this app's words.
DoayaLookLabels lookLabels(AppLocalizations l) => DoayaLookLabels(
  style: l.lookStyle,
  styles: [
    l.lookStyleGlass,
    l.lookStyleFlat,
    l.lookStyleSoft,
    l.lookStyleOutline,
    l.lookStyleContrast,
  ],
  styleNotes: [
    l.lookNoteGlass,
    l.lookNoteFlat,
    l.lookNoteSoft,
    l.lookNoteOutline,
    l.lookNoteContrast,
  ],
  mode: l.lookMode,
  modes: [l.lookModeDark, l.lookModeLight, l.lookModeBlack, l.lookModeAuto],
  colors: l.lookColors,
  palettes: [
    l.lookPaletteGreen,
    l.lookPaletteNavy,
    l.lookPaletteWine,
    l.lookPaletteViolet,
    l.lookPaletteSky,
    l.lookPaletteRose,
    l.lookPaletteAmber,
    l.lookPaletteOlive,
    l.lookPaletteMint,
    l.lookPaletteSand,
    l.lookPaletteChar,
  ],
  custom: l.lookCustom,
  mainColor: l.lookMain,
  background: l.lookBackground,
  hue: l.lookHue,
  lightness: l.lookLightness,
  details: l.lookDetails,
  corners: l.lookCorners,
  blur: l.lookBlur,
  textSize: l.lookTextSize,
  textSizes: [l.lookSizeSmall, l.lookSizeNormal, l.lookSizeLarge, l.lookSizeXLarge],
  spacing: l.lookSpacing,
  spacings: [l.lookSpacingComfy, l.lookSpacingCompact],
  headingFont: l.lookHeadingFont,
  headingFonts: [l.lookFontAmiri, l.lookFontPlain],
  readability: l.lookReadability,
  readable: l.lookReadable,
  adjusted: l.lookAdjusted,
  sample: l.lookSample,
  sampleButton: l.lookSampleButton,
  sampleWarning: l.lookSampleWarning,
  sampleDanger: l.lookSampleDanger,
  reset: l.lookReset,
);
