"""Phase 3: patients, pharmacy directory and keys, shelf, consultations,
AI log, pickup orders (central server)."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pharmacy_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pharmacy_id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(
        op.f("ix_pharmacy_keys_pharmacy_id"), "pharmacy_keys", ["pharmacy_id"], unique=False
    )
    op.create_table(
        "pharmacy_listings",
        sa.Column("pharmacy_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("hours", sa.String(length=120), nullable=True),
        sa.Column("listed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("pharmacy_id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_pharmacy_listings_city"), "pharmacy_listings", ["city"], unique=False)
    op.create_table(
        "shelf_items",
        sa.Column("pharmacy_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("trade_name", sa.String(length=200), nullable=False),
        sa.Column("arabic_name", sa.String(length=200), nullable=True),
        sa.Column("active_ingredient", sa.String(length=200), nullable=True),
        sa.Column("strength", sa.String(length=60), nullable=True),
        sa.Column("form", sa.String(length=60), nullable=True),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("prescription_only", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sa.String(length=300), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("pharmacy_id", "product_id"),
    )
    op.create_table(
        "consultations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("pharmacy_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("urgent", sa.Boolean(), nullable=False),
        sa.Column("red_flag", sa.String(length=40), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("handled_by", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "consultations_pharmacy_updated",
        "consultations",
        ["pharmacy_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consultations_patient_id"), "consultations", ["patient_id"], unique=False
    )
    op.create_table(
        "patient_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("pharmacy_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("pharmacist_note", sa.String(length=1000), nullable=True),
        sa.Column("handled_by", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_orders_patient_id"), "patient_orders", ["patient_id"], unique=False
    )
    op.create_index(
        "patient_orders_pharmacy_updated",
        "patient_orders",
        ["pharmacy_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "patient_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=1), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column("pharmacy_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "patient_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_patient_sessions_user_id"), "patient_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "ai_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_log_consultation_id"), "ai_log", ["consultation_id"], unique=False)
    op.create_index(op.f("ix_ai_log_kind"), "ai_log", ["kind"], unique=False)
    op.create_table(
        "consult_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("text", sa.String(length=4000), nullable=False),
        sa.Column("quick_replies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consult_messages_consultation_id"),
        "consult_messages",
        ["consultation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consult_messages_consultation_id"), table_name="consult_messages")
    op.drop_table("consult_messages")
    op.drop_index(op.f("ix_ai_log_kind"), table_name="ai_log")
    op.drop_index(op.f("ix_ai_log_consultation_id"), table_name="ai_log")
    op.drop_table("ai_log")
    op.drop_index(op.f("ix_patient_sessions_user_id"), table_name="patient_sessions")
    op.drop_table("patient_sessions")
    op.drop_table("patient_profiles")
    op.drop_index("patient_orders_pharmacy_updated", table_name="patient_orders")
    op.drop_index(op.f("ix_patient_orders_patient_id"), table_name="patient_orders")
    op.drop_table("patient_orders")
    op.drop_index(op.f("ix_consultations_patient_id"), table_name="consultations")
    op.drop_index("consultations_pharmacy_updated", table_name="consultations")
    op.drop_table("consultations")
    op.drop_table("shelf_items")
    op.drop_index(op.f("ix_pharmacy_listings_city"), table_name="pharmacy_listings")
    op.drop_table("pharmacy_listings")
    op.drop_index(op.f("ix_pharmacy_keys_pharmacy_id"), table_name="pharmacy_keys")
    op.drop_table("pharmacy_keys")
    # ### end Alembic commands ###
